directories:
  output: dist-electron
  buildResources: build
appId: com.modern.browser
productName: Modern Browser
win:
  target: nsis
  icon: public/icon.ico
files:
  - filter:
      - dist/**/*
      - electron/**/*
extraResources:
  - from: electron/preload.cjs
    to: preload.cjs
electronVersion: 29.4.6
